apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-config.yml
  - postgres.yml
  - ai-copilot.yml
  - incident-service.yml
  - incident-rbac.yml
  - frontend.yml
  - prometheus-rbac.yml
