[k3s_nodes]
sre-node ansible_host=16.16.175.206 ansible_user=ubuntu ansible_ssh_private_key_file="C:/Users/raman/Desktop/trainer module/SRE PROJECT/sre-copilot-key.pem"

[k3s_nodes:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
